import {
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  BookMarked,
  BookOpen,
  Brain,
  Check,
  CheckCircle,
  CheckSquare,
  ChevronLeft,
  ChevronRight,
  CircleDot,
  Clock,
  Eye,
  FileQuestion,
  FileText,
  GraduationCap,
  History,
  Info,
  LayoutDashboard,
  Link,
  ListChecks,
  Loader2,
  Lock,
  LogIn,
  LogOut,
  Mail,
  Menu,
  Pencil,
  PenTool,
  Play,
  Plus,
  PlusCircle,
  Save,
  Search,
  Send,
  Sparkles,
  Square,
  Target,
  Trash2,
  Trophy,
  UploadCloud,
  User,
  UserPlus,
  Users,
  X,
} from "lucide-react";

const icons = {
  "alert-circle": AlertCircle,
  "alert-triangle": AlertTriangle,
  "arrow-left": ArrowLeft,
  "book-marked": BookMarked,
  "book-open": BookOpen,
  brain: Brain,
  check: Check,
  "check-circle": CheckCircle,
  "check-square": CheckSquare,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "circle-dot": CircleDot,
  clock: Clock,
  eye: Eye,
  "file-question": FileQuestion,
  "file-text": FileText,
  "graduation-cap": GraduationCap,
  history: History,
  info: Info,
  "layout-dashboard": LayoutDashboard,
  link: Link,
  "list-checks": ListChecks,
  "loader-2": Loader2,
  lock: Lock,
  "log-in": LogIn,
  "log-out": LogOut,
  mail: Mail,
  menu: Menu,
  pencil: Pencil,
  "pen-tool": PenTool,
  play: Play,
  plus: Plus,
  "plus-circle": PlusCircle,
  save: Save,
  search: Search,
  send: Send,
  sparkles: Sparkles,
  square: Square,
  target: Target,
  "trash-2": Trash2,
  trophy: Trophy,
  "upload-cloud": UploadCloud,
  user: User,
  "user-plus": UserPlus,
  users: Users,
  x: X,
};

const Icon = ({ name, ...props }) => {
  const Component = icons[name] || Info;
  return <Component {...props} />;
};

export default Icon;
